@base_url = http://127.0.0.1:54321/functions/v1
@token = ADD_TOKEN_HERE


### List all timeline items | Filter: type {page?: number; size?: number; unpaged?: boolean; jobPositionId?: string; type: TimelineType}
### IF page/size are present then should return filtering it
### IF unpaged=true then it should return all records
### And error if page/size nor unpaged are present
### should select only: id, position_id, title, type, text, interview_scheduled_date, interview_interviewer_name, interview_score, created_at 
GET {{base_url}}/api/timeline-items?page=0&size=20&jobPositionId=9ba19541-8c9d-4984-9350-e654b4df780d&type=COVER_LETTER
Content-Type: application/json
Authorization: Bearer {{token}}

### Get a specific timeline item
GET {{base_url}}/api/timeline-items/9ba19541-8c9d-4984-9350-e654b4df780d
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a timeline type NOTE; Type TimelineCreateText
POST {{base_url}}/api/timeline-items/note
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "positionId": "78d6f20b-5180-49e5-9f8e-9ca1eeb830ae",
  "title": "Interview stages overview",
  "text": "1) a screening with recruinter; 2) deep dive on the technical background; 3) Interview with hiring manager; 4) Final round with CEO"
}

### Create a timeline type COVER_LETTER; Type TimelineCoverLetter
POST {{base_url}}/api/timeline-items/cover-letter
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "positionId":"a1d89ebf-9c40-435b-833a-c65e1b1a2a96",
  "customInstructions":"Use the information in my cv, mathing the main points from the job description and write me a cover letter."
}

### Create a timeline type LINKEDIN_INTRO; Type TimelineLinkedinIntro
POST {{base_url}}/api/timeline-items/linkedin-intro
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "positionId":"a1d89ebf-9c40-435b-833a-c65e1b1a2a96",
  "greeting":"hi there!",
  "customInstructions":"Create a short and direct introductory message. Highlight my experience and the aspects I have in common with the position."
}

### Create a timeline type REPLY_EMAIL; Type TimelineReplyEmail
POST {{base_url}}/api/timeline-items/reply-email
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "positionId":"a1d89ebf-9c40-435b-833a-c65e1b1a2a96",
  "emailBody":"Hello, Thanks for applying for Rochec Inc, we are glad to inform you that we would like to book a meeting. Would you be able to send us 3 timeslots on Monday or Tuesday. Please read the attached candidate manual. Looking forward to see you.",
  "customInstructions":"Please keep the tone warm and enthusiastic, but still professional. Mention that I believe my background aligns well with the position."
}

### Create a timeline type INTERVIEW_ANALYSE; Type TimelineInterviewAnalyse
POST {{base_url}}/api/timeline-items/analyse-interview
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "positionId":"08c2f59a-4feb-4c7c-90d5-f885efc8ef79",
  "interviewPath":"fa9851bd-ec29-4dc9-82e1-dcebe40aeebd/1754653862227.mp3"
}

### Update the custom instructions; TimelineCustomInstructionsUpdate
PATCH {{base_url}}/api/timeline-items/99c60056-083c-40d6-af94-597362633913/custom-instructions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "customInstructions": "Mark is my name, the recruiter is paul "
}

### Delete a timeline item
DELETE {{base_url}}/api/timeline-items/9ba19541-8c9d-4984-9350-e654b4df780d
Content-Type: application/json
Authorization: Bearer {{token}}
