@base_url = http://127.0.0.1:54321/functions/v1
@token = ADD_TOKEN_HERE


### List all job positions
GET {{base_url}}/api/job-positions
Content-Type: application/json
Authorization: Bearer {{token}}

### Get a specific job position
GET {{base_url}}/api/job-positions/9ba19541-8c9d-4984-9350-e654b4df780d
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a job position by URL
POST {{base_url}}/api/job-positions/by-url
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "profileId": "78d6f20b-5180-49e5-9f8e-9ca1eeb830ae",
  "jobUrl": "https://www.tesla.com/en_GB/careers/search/job/account-manager-corporate-midlands-north-246987"
}

### Create a job position by raw HTML description
POST {{base_url}}/api/job-positions/by-description
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "profileId": "78d6f20b-5180-49e5-9f8e-9ca1eeb830ae",
  "jobDescription": "<div><b>facebook</b>Software engineer between 100k-120k you are a nice dev</div>"
}

### Update a job position
PATCH {{base_url}}/api/job-positions/78d6f20b-5180-49e5-9f8e-9ca1eeb830ae
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "careerProfileId": "78d6f20b-5180-49e5-9f8e-9ca1eeb830ae",
  "companyName": "Teya",
  "companyWebsite": "https://teya.com",
  "jobUrl": "https://teya.com/jobs/123",
  "jobTitle": "Backend Engineer",
  "expectedSalary": "€60k-€80k"
}

### Delete a job position
DELETE {{base_url}}/api/job-positions/9ba19541-8c9d-4984-9350-e654b4df780d
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a job position by raw HTML description
PATCH  {{base_url}}/api/job-positions/archive
Content-Type: application/json
Authorization: Bearer {{token}}

["a1d89ebf-9c40-435b-833a-c65e1b1a2a96"]
